CREATE DATABASE QLBH;

GO

DROP TABLE IF EXISTS CungUng;
DROP TABLE IF EXISTS SanPham;
DROP TABLE IF EXISTS CongTy;
GO

USE QLBH;

GO

CREATE TABLE CongTy(
	MaCT NVARCHAR(30) PRIMARY KEY NOT NULL,
	TenCT NVARCHAR(30) NOT NULL,
	TrangThai NVARCHAR(20) NOT NULL,
	ThanhPho NVARCHAR(40) NOT NULL
)
GO


CREATE TABLE SanPham(
	MaSP NCHAR(30) PRIMARY KEY NOT NULL,
	TenSP NVARCHAR(30) NOT NULL,
	CONSTRAINT unq_TenS UNIQUE(TenSP),
	MauSac NVARCHAR(10) DEFAULT (N'Do'), --Contraint la kh dc trung lap
	Gia MONEY,
	SoLuongCo INT
)
GO

CREATE TABLE CungUng(
	MaCT NVARCHAR(30) NOT NULL,
	MaSP NCHAR(30) NOT NULL,
	CONSTRAINT PK_CungUng PRIMARY KEY(MaCT, MaSP),
	CONSTRAINT FK_CungUng_CongTy FOREIGN KEY(MaCT)
		REFERENCES CongTy(MaCT),
	CONSTRAINT FK_CungUng_SanPham FOREIGN KEY(MaSP)
		REFERENCES SanPham(MaSP),
	SoLuongCo INT,
	CONSTRAINT check_SLC CHECK(SoLuongCo > 0)
)
GO
