CREATE DATABASE QLSINHVIEN
GO

DROP TABLE IF EXISTS SINHVIEN;
DROP TABLE IF EXISTS KHOA;
DROP TABLE IF EXISTS LOP;
GO

USE QLSINHVIEN
GO

CREATE TABLE KHOA
(
	MaKhoa NCHAR(10) PRIMARY KEY NOT NULL,
	TenKhoa NVARCHAR(30) NOT NULL,
	SoDT NVARCHAR(15)
)
GO

CREATE TABLE LOP
(
	MaLop NCHAR(10) PRIMARY KEY NOT NULL,
	TenLop NVARCHAR(30) NOT NULL,
	MaKhoa NCHAR(10) NOT NULL,
	CONSTRAINT FK_Lop_Khoa FOREIGN KEY(MaKhoa)
		REFERENCES KHOA(MaKhoa)
)
GO

CREATE TABLE SINHVIEN
(
	MaSV NCHAR(10) PRIMARY KEY NOT NULL,
	HoDem NVARCHAR(10) NOT NULL,
	Ten NVARCHAR(10) NOT NULL,
	NgaySinh DATE,
	GioiTinh NVARCHAR(20),
	QUEQUAN NVARCHAR(30),
	MaLop NCHAR(10) NOT NULL,
	CONSTRAINT FK_SinhVien_LOP FOREIGN KEY(MaLop)
		REFERENCES LOP(MaLop)
)
GO

--Them du lieu vao cac bang
INSERT INTO KHOA (MaKhoa, TenKhoa, SoDT) VALUES
('CNTT', 'CONG NGHE THONG TIN', '2991031'),
('KHMT', 'KHOA HOC MAY TINH', '199201'),
('KTPM', 'KY THUAT PHAN MEM', '191031'),
('KTHH', 'CONG NGHE HOA HOC', '39291031');
GO

-- Thêm dữ liệu vào LOP
INSERT INTO LOP (MaLop, TenLop, MaKhoa) VALUES
('L01', 'TOI UU HOA', 'KHMT'),
('L02', 'KIEN TRUC MT', 'CNTT'),
('L03', 'TIENG ANH CNTT', 'KTPM'),
('L04', 'HOA HOC DAI CUONG', 'KTHH');
GO


INSERT INTO SINHVIEN([MaSV],[HoDem],[Ten],[NgaySinh],[GioiTinh],[QUEQUAN],[MaLop]) VALUES
('202130102','Pham','Kiet', '02-20-2017','Nam','Nghe An','L01'),
('290102032','Nguyen','An', '03-12-2017','Nam','Ha Tinh','L02'),
('929102212','Tran','Nam', '04-25-2017','Nam','Thanh Hoa','L03'),
('132830102','Pham','Nhi', '08-19-2017','Nu','Nghe An','L04'),
('128830102','Vu','Duong', '02-21-2017','Nam','Bac Ninh','L01')

SELECT * from KHOA
SELECT * from LOP
SELECT * from SINHVIEN

--update (sua)
UPDATE LOP
SET [TenLop] = 'Andorid'
WHERE TenLop = 'TOI UU HOA'

--delete (xoa)
--DELETE FROM KHOA
--WHERE MaKhoa = 'KTPM'
SELECT * FROM LOP WHERE MaKhoa = 'KTPM';  --tim

--xoa nhung sinh vien hoc lop HOA HOC DAI CUONG
DELETE FROM SINHVIEN FROM LOP
WHERE SINHVIEN.MaLop = LOP.MaLop and TenLop = 'HOA HOC DAI CUONG'
--trong bai nay la pham nhi bi xoa